### ISSUE TITLE
Offsets file override for long-term non-recompile support

### ISSUE THREAD

**Issue by Meowchestra** [trotlinebeercan/CameraHackTool#2]
Similar to jayotterbein/FFXIV-Zoom-Hack so you can just change the offsets value by file if there is a new game update that breaks it instead of needing to release a new version and recompile every time?

i.e.
https://github.com/jayotterbein/FFXIV-Zoom-Hack/blob/master/Offsets.xml

**Comment by trotlinebeercan** [comment]
https://github.com/trotlinebeercan/CameraHackTool/commit/de201fa1ccf5726d96db042b46f38d6521100b08

This work is already in progress. 👍

**Comment by trotlinebeercan** [comment]
currently, offsets are read from server. updated application version is not yet supported. https://github.com/trotlinebeercan/CameraHackTool/commit/e09a49a91d91793429401e6573416f4f23cc1bf5

**Comment by Meowchestra** [comment]
I'll let you decide what to do with this ticket since I'm not sure if it's fully implemented or not yet.
