### ISSUE TITLE
Re-scan for new processes when you click select process.

### ISSUE THREAD

**Issue by Meowchestra** [trotlinebeercan/CameraHackTool#3]
Would it be possible to make it so clicking select process re-scans for new processes to add to the list if you've opened new games since launching it? Currently you have to relaunch CHT if you open more clients. It doesn't detect the newer pids.

**Comment by trotlinebeercan** [comment]
This should already be working - probably a simple bug fix.

**Comment by trotlinebeercan** [comment]
fixed in the latest commit: https://github.com/trotlinebeercan/CameraHackTool/commit/e09a49a91d91793429401e6573416f4f23cc1bf5

**Comment by Meowchestra** [comment]
Seems to be fixed as of v1.3, thanks.
