### ISSUE TITLE
Silent crash when closing a hooked client with CameraHackTool open.

### ISSUE THREAD

**Issue by Meowchestra** [trotlinebeercan/CameraHackTool#4]
I was able to reproduce CHT randomly crashing if you close down a hooked client while it's still attached and running. This makes it so existing clients lose their rollback location since when you re-open, they are already in the sky.

**Comment by trotlinebeercan** [comment]
Hmm. I think I can detect when a client closes in memory, and have the executing thread shutdown. Not sure if I'll find a way to 100% cover this issue, but I can try some things out.

**Comment by trotlinebeercan** [comment]
fixed in the latest commit: https://github.com/trotlinebeercan/CameraHackTool/commit/e09a49a91d91793429401e6573416f4f23cc1bf5

**Comment by Meowchestra** [comment]
Seems to be fixed as of v1.3, thanks.
