### ISSUE TITLE
CameraHackTool loses track of active characters whom disconnected.

### ISSUE THREAD

**Issue by Meowchestra** [trotlinebeercan/CameraHackTool#5]
I was able to produce another crashing issue / bug with CameraHackTool v1.3. This time with it having lingering clients listed, no longer available.

This is the reproduction steps I took.

* Launched & logged in to 10 clients.
* Opened CHT & clicked Select Process
* Selected "Open All Processes"
* Selected my main character from the current characters box and clicked "remove"
* Clicked "Apply to All Processes"
* Launched & logged in to 5 _more_ clients.
* Clicked "select process"
* Manually selected the 5 new processes, ignoring my main, and clicking "open this process".
* Manually double clicked the 5 new characters to toggle enabling individually one at a time.
* Repeated the same steps again to log into _5 more clients_, totaling 20 clients with 19 hooked.
* Started to log out clients after a while by hitting Exit Game and then OK until I only had 7 clients remaining logged in (1 main + 6 hooked)
* CHT was removing characters fine but then broke near the end. It listed 9 characters in the "Current Characters" active box, with 3 of them being the last 3 I exited the game for (part of the initial first 10 logged in, last to logout).
* Upon trying to double click to toggle one of the invalid characters it thought was still alive, CHT crashed and closed.

I'm guessing the break happens when you go from ``Open All Processes`` to individually selecting characters and clicking ``Open This Process``? With it forgetting the previous clients opened with the other button.

**Comment by trotlinebeercan** [comment]
let me know if the issue is still present in v1.4

**Comment by Meowchestra** [comment]
Sorry, haven't had time to fully re-test but I did notice that if you have clients hooked but toggled off, they don't remove themselves properly when you close the game. It remains in the CHT window and if you toggle it on, it crashes.

**Comment by Meowchestra** [comment]
@trotlinebeercan An example.

![link](https://i.imgur.com/YhLY37z.png)

* Logged into 8 accounts.
* Opened CHT
* Select Process
* Apply to All Processes
* Selected main character and removed
* Apply To All Processes

Time passes.

* Stop All
* Start logging out of clients. (In my screenshot, I had no clients actively running.)
* Clients remain in CHT - not removed from CHT on exit if toggled off. 
* Toggling the individual character not available or all processes crashes CHT.

**Comment by Meowchestra** [comment]
Found another bug. I logged into 21 clients, used CHT to toggle 20 of them. Then started to close 2/3rds of them (didn't toggle them). It properly removed it from the current characters list. However when I re-logged into one of the clients I accidentally closed and went to select process again, it showed all the inactive processes no longer running.

I didn't try adding the dead processes, just the one I re-logged on because I didn't want CHT to crash.
![link20](https://i.imgur.com/HIKWt41.png)

**Comment by Meowchestra** [comment]
Closing for upstream repo ticket priority.
